### ISSUE TITLE
Error message when clearing quick form location

### ISSUE THREAD

**Issue by mstenta** [Rothamsted-Ecoinformatics/farm_rothamsted#518]
This is probably minor, but it came up in my server's error logs so I'll document it here and we can see if it needs to be fixed:

```
TypeError: array_column(): Argument #1 ($array) must be of type array, null given in /opt/drupal/web/modules/farm_rothamsted/modules/farm_rothamsted_quick/src/Plugin/QuickForm/QuickExperimentFormBase.php on line 290 #0 /opt/drupal/web/modules/farm_rothamsted/modules/farm_rothamsted_quick/src/Plugin/QuickForm/QuickExperimentFormBase.php(290): array_column()\n#1 /opt/drupal/web/modules/farm_rothamsted/modules/farm_rothamsted_quick/src/Plugin/QuickForm/QuickCombineHarvest.php(49): Drupal\\farm_rothamsted_quick\\Plugin\\QuickForm\\QuickExperimentFormBase->buildForm()\n#2 /opt/drupal/web/profiles/farm/modules/core/quick/src/Form/QuickForm.php(105): Drupal\\farm_rothamsted_quick\\Plugin\\QuickForm\\QuickCombineHarvest->buildForm()\n#3 [internal function]: Drupal\\farm_quick\\Form\\QuickForm->buildForm()\n#4 /opt/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(536): call_user_func_array()\n#5 /opt/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(375): Drupal\\Core\\Form\\FormBuilder->retrieveForm()\n#6 /opt/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(633): Drupal\\Core\\Form\\FormBuilder->rebuildForm()\n#7 /opt/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(325): Drupal\\Core\\Form\\FormBuilder->processForm()\n#8 /opt/drupal/web/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\\Core\\Form\\FormBuilder->buildForm()\n#9 [internal function]: Drupal\\Core\\Controller\\FormController->getContentResult()\n#10 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()\n#11 /opt/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(580): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()\n#12 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\\Core\\Render\\Renderer->executeInRenderContext()\n#13 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()\n#14 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(169): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()\n#15 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()\n#16 /opt/drupal/web/modules/simple_oauth/src/HttpMiddleware/BasicAuthSwap.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handle()\n#17 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Drupal\\simple_oauth\\HttpMiddleware\\BasicAuthSwap->handle()\n#18 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\\Core\\StackMiddleware\\Session->handle()\n#19 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\\Core\\StackMiddleware\\KernelPreHandle->handle()\n#20 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\\Core\\StackMiddleware\\ReverseProxyMiddleware->handle()\n#21 /opt/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\\Core\\StackMiddleware\\NegotiationMiddleware->handle()\n#22 /opt/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(718): Stack\\StackedHttpKernel->handle()\n#23 /opt/drupal/web/index.php(19): Drupal\\Core\\DrupalKernel->handle()\n#24 {main}
```

It happened a few times on the following paths:

- /quick/combine_harvest
- /quick/trailer_harvest

**Comment by aislinnpearson** [comment]
Okay, thanks @mstenta. I spoke to @paul121 about this today and will add it to the current milestone, but can also discuss next week if needed.

**Comment by mstenta** [comment]
Here's a different one that just popped up - not the same error but maybe also easy to fix:

```
Warning: Undefined property: stdClass::$column_id in farm_rothamsted_experiment_views_pre_view() (line 45 of /opt/drupal/web/modules/farm_rothamsted/modules/farm_rothamsted_experiment/farm_rothamsted_experiment.views_execution.inc) #0 /opt/drupal/web/core/includes/bootstrap.inc(347): _drupal_error_handler_real()
#1 /opt/drupal/web/modules/farm_rothamsted/modules/farm_rothamsted_experiment/farm_rothamsted_experiment.views_execution.inc(45): _drupal_error_handler()
#2 [internal function]: farm_rothamsted_experiment_views_pre_view()
#3 /opt/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(426): call_user_func_array()
#4 /opt/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(405): Drupal\Core\Extension\ModuleHandler->Drupal\Core\Extension\{closure}()
#5 /opt/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(433): Drupal\Core\Extension\ModuleHandler->invokeAllWith()
#6 /opt/drupal/web/core/modules/views/src/ViewExecutable.php(1691): Drupal\Core\Extension\ModuleHandler->invokeAll()
#7 /opt/drupal/web/core/modules/views/src/ViewExecutable.php(1632): Drupal\views\ViewExecutable->preExecute()
#8 /opt/drupal/web/core/modules/views/src/Element/View.php(81): Drupal\views\ViewExecutable->executeDisplay()
#9 [internal function]: Drupal\views\Element\View::preRenderViewElement()
#10 /opt/drupal/web/core/lib/Drupal/Core/Security/DoTrustedCallbackTrait.php(101): call_user_func_array()
#11 /opt/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(788): Drupal\Core\Render\Renderer->doTrustedCallback()
#12 /opt/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(374): Drupal\Core\Render\Renderer->doCallback()
#13 /opt/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(204): Drupal\Core\Render\Renderer->doRender()
#14 /opt/drupal/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(242): Drupal\Core\Render\Renderer->render()
#15 /opt/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(580): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}()
#16 /opt/drupal/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(243): Drupal\Core\Render\Renderer->executeInRenderContext()
#17 /opt/drupal/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(132): Drupal\Core\Render\MainContent\HtmlRenderer->prepare()
#18 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse()
#19 [internal function]: Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray()
#20 /opt/drupal/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func()
#21 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(174): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()
#22 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#23 /opt/drupal/web/modules/simple_oauth/src/HttpMiddleware/BasicAuthSwap.php(68): Symfony\Component\HttpKernel\HttpKernel->handle()
#24 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap->handle()
#25 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle()
#26 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#27 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#28 /opt/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#29 /opt/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(718): Stack\StackedHttpKernel->handle()
#30 /opt/drupal/web/index.php(19): Drupal\Core\DrupalKernel->handle()
```

**Comment by aislinnpearson** [comment]
Do you want me to make two issues for this @paul121?

**Comment by paul121** [comment]
Okay, I think the first error is happening during the AJAX reload when clearing a location from the quick form's location field. In most cases this AJAX is only triggered when adding location(s) and an array is returned. But if a user clears all locations in the form then `NULL` is returned and it throws this error.

**Comment by paul121** [comment]
Creating a new issue for the second error #527
