### ISSUE TITLE
Error loading column_id in plan column_descriptors

### ISSUE THREAD

**Issue by paul121** [Rothamsted-Ecoinformatics/farm_rothamsted#527]
Here's a different one that just popped up - not the same error but maybe also easy to fix:

```
Warning: Undefined property: stdClass::$column_id in farm_rothamsted_experiment_views_pre_view() (line 45 of /opt/drupal/web/modules/farm_rothamsted/modules/farm_rothamsted_experiment/farm_rothamsted_experiment.views_execution.inc) #0 /opt/drupal/web/core/includes/bootstrap.inc(347): _drupal_error_handler_real()
#1 /opt/drupal/web/modules/farm_rothamsted/modules/farm_rothamsted_experiment/farm_rothamsted_experiment.views_execution.inc(45): _drupal_error_handler()
#2 [internal function]: farm_rothamsted_experiment_views_pre_view()
#3 /opt/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(426): call_user_func_array()
#4 /opt/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(405): Drupal\Core\Extension\ModuleHandler->Drupal\Core\Extension\{closure}()
#5 /opt/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(433): Drupal\Core\Extension\ModuleHandler->invokeAllWith()
#6 /opt/drupal/web/core/modules/views/src/ViewExecutable.php(1691): Drupal\Core\Extension\ModuleHandler->invokeAll()
#7 /opt/drupal/web/core/modules/views/src/ViewExecutable.php(1632): Drupal\views\ViewExecutable->preExecute()
#8 /opt/drupal/web/core/modules/views/src/Element/View.php(81): Drupal\views\ViewExecutable->executeDisplay()
#9 [internal function]: Drupal\views\Element\View::preRenderViewElement()
#10 /opt/drupal/web/core/lib/Drupal/Core/Security/DoTrustedCallbackTrait.php(101): call_user_func_array()
#11 /opt/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(788): Drupal\Core\Render\Renderer->doTrustedCallback()
#12 /opt/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(374): Drupal\Core\Render\Renderer->doCallback()
#13 /opt/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(204): Drupal\Core\Render\Renderer->doRender()
#14 /opt/drupal/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(242): Drupal\Core\Render\Renderer->render()
#15 /opt/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(580): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}()
#16 /opt/drupal/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(243): Drupal\Core\Render\Renderer->executeInRenderContext()
#17 /opt/drupal/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(132): Drupal\Core\Render\MainContent\HtmlRenderer->prepare()
#18 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse()
#19 [internal function]: Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray()
#20 /opt/drupal/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func()
#21 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(174): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()
#22 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#23 /opt/drupal/web/modules/simple_oauth/src/HttpMiddleware/BasicAuthSwap.php(68): Symfony\Component\HttpKernel\HttpKernel->handle()
#24 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap->handle()
#25 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle()
#26 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#27 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#28 /opt/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#29 /opt/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(718): Stack\StackedHttpKernel->handle()
#30 /opt/drupal/web/index.php(19): Drupal\Core\DrupalKernel->handle()
```

_Originally posted by @mstenta in https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/518#issuecomment-1653530777_

**Comment by paul121** [comment]
This might be a bit more of a complicated issue. @mstenta could you possibly share the path that this happened on? It should be the Plan->Plots page and I'm particularly interested to know which plan this was for (maybe DM me the info for privacy).

https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/blob/baae0643e3888f241dbaafdc8b5235eee6422d3c/modules/farm_rothamsted_experiment/farm_rothamsted_experiment.views_execution.inc#L29-L47

The module is making the assumption we'll always have a `column_id` for each column in `plan.column_descriptors` JSON (which we should!). Adding an exception here to check & skip would fix the error but ultimately doesn't solve the issue of why there is no `column_id`... The `plan.column_descriptors` field is populated by the Plan variables form so perhaps we are missing some validation and a bad file was uploaded?

**Comment by mstenta** [comment]
> @mstenta could you possibly share the path that this happened on? It should be the Plan->Plots page and I'm particularly interested to know which plan this was for (maybe DM me the info for privacy).

Yes will do. :+1:

**Comment by paul121** [comment]
Interesting. I see this experiment has an "empty" variable column on the Variables page. Looking via the API I see there is an empty column level in the JSON field:

![Screenshot from 2023-07-31 11-00-43](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/3116995/48f2ab6c-b8d5-4894-8055-a893a0c23295)
![Screenshot from 2023-07-31 10-57-25](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/3116995/0b153d0d-7c4f-4f9e-bdcc-7870ada8397e)

However, the current column and column levels CSVs don't seem to have any blank rows or missing information and look OK. The revisions look like this plan might have been created in 10/2022 so it is possible the CSVs have since been changed or there was a bug in the csv importer back then (this code/process has since changed but still saves to the same JSON format in the DB).

I'll look at manually updating this one via API then lets see if we see this error occurs again

**Comment by paul121** [comment]
Okay I've updated this via the API, here is a rough script:

```python
import json
from farmOS import farmOS

client = farmOS(....) # get farmOS.py client
client.authorize()
plan = client.resource.get_id('plan', 'rothamsted_experiment', 'UUID HERE')
columns = plan["data"]["attributes"]["column_descriptors"]
cols = json.loads(columns)

# Check columns
len(cols) # Prints 13
cols[0] # Displays empty column json from above screenshot
cols.remove(cols[0]) # remove 0 index
len(cols) # Prints 12

# Update plan
 new_cols = json.dumps(cols) # convert to json string
 plan_copy = {
     "id": 'UUID',
    "attributes": {
        "column_descriptors": new_cols
    },
}

# Send
try:
    client.resource.send('plan', 'rothamsted_experiment', plan_copy)
except Exception as e:
    print(e.response.text)
```

**Comment by paul121** [comment]
@mstenta confirmed the error seems to be gone :+1:
