### ISSUE TITLE
TypeError: ExperimentPlotForm::updatePlotBatch(): Argument #3 ($experiment_code) must be of type string, null given

### ISSUE THREAD

**Issue by mstenta** [Rothamsted-Ecoinformatics/farm_rothamsted#530]
Appeared in server logs:

```
TypeError: Drupal\\farm_rothamsted_experiment\\Form\\ExperimentPlotForm::updatePlotBatch(): Argument #3 ($experiment_code) must be of type string, null given, called in /opt/drupal/web/core/includes/batch.inc on line 295 in /opt/drupal/web/modules/farm_rothamsted/modules/farm_rothamsted_experiment/src/Form/ExperimentPlotForm.php on line 148 #0 /opt/drupal/web/core/includes/batch.inc(295): Drupal\\farm_rothamsted_experiment\\Form\\ExperimentPlotForm::updatePlotBatch()\n#1 /opt/drupal/web/core/includes/batch.inc(137): _batch_process()\n#2 /opt/drupal/web/core/includes/batch.inc(93): _batch_do()\n#3 /opt/drupal/web/core/modules/system/src/Controller/BatchController.php(55): _batch_page()\n#4 [internal function]: Drupal\\system\\Controller\\BatchController->batchPage()\n#5 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()\n#6 /opt/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(580): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()\n#7 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\\Core\\Render\\Renderer->executeInRenderContext()\n#8 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()\n#9 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(169): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()\n#10 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()\n#11 /opt/drupal/web/modules/simple_oauth/src/HttpMiddleware/BasicAuthSwap.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handle()\n#12 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Drupal\\simple_oauth\\HttpMiddleware\\BasicAuthSwap->handle()\n#13 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\\Core\\StackMiddleware\\Session->handle()\n#14 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\\Core\\StackMiddleware\\KernelPreHandle->handle()\n#15 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\\Core\\StackMiddleware\\ReverseProxyMiddleware->handle()\n#16 /opt/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\\Core\\StackMiddleware\\NegotiationMiddleware->handle()\n#17 /opt/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(718): Stack\\StackedHttpKernel->handle()\n#18 /opt/drupal/web/index.php(19): Drupal\\Core\\DrupalKernel->handle()\n#19 {main}, referer: https://rothamstedfarm.farmos.net/batch?id=48&op=start
```

**Comment by paul121** [comment]
I believe this happened because the Plan doesn't have a study period ID (previously experiment code). It is assumed that the experiment will have this field populated before making plots: plots requires an experiment boundary, and the experiment boundary form requires a study period ID. But you could still delete the study period ID after making a boundary, so we should make it a more explicit requirement in the Plot form.

**Comment by aislinnpearson** [comment]
> I believe this happened because the Plan doesn't have a study period ID (previously experiment code). It is assumed that the experiment will have this field populated before making plots: plots requires an experiment boundary, and the experiment boundary form requires a study period ID

I think I created this issue doing exactly that. 

 > But you could still delete the study period ID after making a boundary, so we should make it a more explicit requirement in the Plot form.

Agreed. Please can we make the Study ID a required field on the proposals as discussed. It is especially important if we are going to create new plots for every study year and this code is currently what links them.

**Comment by aislinnpearson** [comment]
HI @paul121,

I don't know if this is related but I am getting an error when I try to add experiment boundaries (see below).

Let me know if it is not related and I can open a new issue...

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/2d141827-49d9-4dd3-9f87-e27fc92454db)

**Comment by mstenta** [comment]
Hi @aislinnpearson - I just saw the error notification come in for this. It is caused by this issue, which is still open: #535

**Comment by aislinnpearson** [comment]
Okay, thanks @mstenta :)
