### ISSUE TITLE
TypeError: QuickExperimentFormBase::getTermTreeOptions(): Argument #2 ($parent) must be of type int, string given

### ISSUE THREAD

**Issue by mstenta** [Rothamsted-Ecoinformatics/farm_rothamsted#531]
This error appeared in logs last night, coming from the spraying quick form:

```
TypeError: Drupal\\farm_rothamsted_quick\\Plugin\\QuickForm\\QuickExperimentFormBase::getTermTreeOptions(): Argument #2 ($parent) must be of type int, string given, called in /opt/drupal/web/modules/farm_rothamsted/modules/farm_rothamsted_quick/src/Plugin/QuickForm/QuickExperimentFormBase.php on line 521 in /opt/drupal/web/modules/farm_rothamsted/modules/farm_rothamsted_quick/src/Traits/QuickTaxonomyOptionsTrait.php on line 73 #0 /opt/drupal/web/modules/farm_rothamsted/modules/farm_rothamsted_quick/src/Plugin/QuickForm/QuickExperimentFormBase.php(521): Drupal\\farm_rothamsted_quick\\Plugin\\QuickForm\\QuickExperimentFormBase->getTermTreeOptions()\n#1 /opt/drupal/web/modules/farm_rothamsted/modules/farm_rothamsted_quick/src/Plugin/QuickForm/QuickSpraying.php(61): Drupal\\farm_rothamsted_quick\\Plugin\\QuickForm\\QuickExperimentFormBase->buildForm()\n#2 /opt/drupal/web/profiles/farm/modules/core/quick/src/Form/QuickForm.php(105): Drupal\\farm_rothamsted_quick\\Plugin\\QuickForm\\QuickSpraying->buildForm()\n#3 [internal function]: Drupal\\farm_quick\\Form\\QuickForm->buildForm()\n#4 /opt/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(536): call_user_func_array()\n#5 /opt/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(375): Drupal\\Core\\Form\\FormBuilder->retrieveForm()\n#6 /opt/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(633): Drupal\\Core\\Form\\FormBuilder->rebuildForm()\n#7 /opt/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(325): Drupal\\Core\\Form\\FormBuilder->processForm()\n#8 /opt/drupal/web/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\\Core\\Form\\FormBuilder->buildForm()\n#9 [internal function]: Drupal\\Core\\Controller\\FormController->getContentResult()\n#10 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()\n#11 /opt/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(580): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()\n#12 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\\Core\\Render\\Renderer->executeInRenderContext()\n#13 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()\n#14 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(169): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()\n#15 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()\n#16 /opt/drupal/web/modules/simple_oauth/src/HttpMiddleware/BasicAuthSwap.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handle()\n#17 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Drupal\\simple_oauth\\HttpMiddleware\\BasicAuthSwap->handle()\n#18 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\\Core\\StackMiddleware\\Session->handle()\n#19 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\\Core\\StackMiddleware\\KernelPreHandle->handle()\n#20 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\\Core\\StackMiddleware\\ReverseProxyMiddleware->handle()\n#21 /opt/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\\Core\\StackMiddleware\\NegotiationMiddleware->handle()\n#22 /opt/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(718): Stack\\StackedHttpKernel->handle()\n#23 /opt/drupal/web/index.php(19): Drupal\\Core\\DrupalKernel->handle()\n#24 {main},
```

**Comment by paul121** [comment]
This was happening when a product type was unselected and the ajax is triggered. Added a catch to make sure that a value is provided before loading the taxonomy tree options.
