### ISSUE TITLE
TypeError: htmlspecialchars(): Argument #1 ($string) must be of type string, array given

### ISSUE THREAD

**Issue by mstenta** [Rothamsted-Ecoinformatics/farm_rothamsted#535]
This error occurred on the /plan/64/create-boundary path on the Harpenden instance.

```
TypeError: htmlspecialchars(): Argument #1 ($string) must be of type string, array given in /opt/drupal/web/core/lib/Drupal/Component/Utility/Html.php on line 432 #0 /opt/drupal/web/core/lib/Drupal/Component/Utility/Html.php(432): htmlspecialchars()\n#1 /opt/drupal/web/core/lib/Drupal/Component/Render/FormattableMarkup.php(270): Drupal\\Component\\Utility\\Html::escape()\n#2 /opt/drupal/web/core/lib/Drupal/Component/Render/FormattableMarkup.php(216): Drupal\\Component\\Render\\FormattableMarkup::placeholderEscape()\n#3 /opt/drupal/web/core/lib/Drupal/Core/StringTranslation/TranslatableMarkup.php(195): Drupal\\Component\\Render\\FormattableMarkup::placeholderFormat()\n#4 /opt/drupal/web/core/lib/Drupal/Component/Utility/ToStringTrait.php(15): Drupal\\Core\\StringTranslation\\TranslatableMarkup->render()\n#5 /opt/drupal/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorageSchema.php(2579): Drupal\\Core\\StringTranslation\\TranslatableMarkup->__toString()\n#6 /opt/drupal/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(1068): Drupal\\Core\\Entity\\Sql\\SqlContentEntityStorageSchema::castValue()\n#7 /opt/drupal/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(1127): Drupal\\Core\\Entity\\Sql\\SqlContentEntityStorage->mapToStorageRecord()\n#8 /opt/drupal/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(1013): Drupal\\Core\\Entity\\Sql\\SqlContentEntityStorage->mapToDataStorageRecord()\n#9 /opt/drupal/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(958): Drupal\\Core\\Entity\\Sql\\SqlContentEntityStorage->saveToSharedTables()\n#10 /opt/drupal/web/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(718): Drupal\\Core\\Entity\\Sql\\SqlContentEntityStorage->doSaveFieldItems()\n#11 /opt/drupal/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(520): Drupal\\Core\\Entity\\ContentEntityStorageBase->doSave()\n#12 /opt/drupal/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(804): Drupal\\Core\\Entity\\EntityStorageBase->save()\n#13 /opt/drupal/web/core/lib/Drupal/Core/Entity/EntityBase.php(339): Drupal\\Core\\Entity\\Sql\\SqlContentEntityStorage->save()\n#14 /opt/drupal/web/modules/farm_rothamsted/modules/farm_rothamsted_experiment/src/Form/ExperimentBoundaryForm.php(181): Drupal\\Core\\Entity\\EntityBase->save()\n#15 [internal function]: Drupal\\farm_rothamsted_experiment\\Form\\ExperimentBoundaryForm->submitForm()\n#16 /opt/drupal/web/core/lib/Drupal/Core/Form/FormSubmitter.php(114): call_user_func_array()\n#17 /opt/drupal/web/core/lib/Drupal/Core/Form/FormSubmitter.php(52): Drupal\\Core\\Form\\FormSubmitter->executeSubmitHandlers()\n#18 /opt/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(597): Drupal\\Core\\Form\\FormSubmitter->doSubmitForm()\n#19 /opt/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(325): Drupal\\Core\\Form\\FormBuilder->processForm()\n#20 /opt/drupal/web/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\\Core\\Form\\FormBuilder->buildForm()\n#21 [internal function]: Drupal\\Core\\Controller\\FormController->getContentResult()\n#22 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()\n#23 /opt/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(580): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()\n#24 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\\Core\\Render\\Renderer->executeInRenderContext()\n#25 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()\n#26 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(169): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()\n#27 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()\n#28 /opt/drupal/web/modules/simple_oauth/src/HttpMiddleware/BasicAuthSwap.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handle()\n#29 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Drupal\\simple_oauth\\HttpMiddleware\\BasicAuthSwap->handle()\n#30 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\\Core\\StackMiddleware\\Session->handle()\n#31 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\\Core\\StackMiddleware\\KernelPreHandle->handle()\n#32 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\\Core\\StackMiddleware\\ReverseProxyMiddleware->handle()\n#33 /opt/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\\Core\\StackMiddleware\\NegotiationMiddleware->handle()\n#34 /opt/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(718): Stack\\StackedHttpKernel->handle()\n#35 /opt/drupal/web/index.php(19): Drupal\\Core\\DrupalKernel->handle()\n#36 {main}
```

**Comment by aislinnpearson** [comment]
Hi @mstenta, @paul121,

I've just got the error again my end. It happens when I try to add an experiment boundary (but definitely have the code in there this time)

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/8b2a4fb7-276d-4375-97f1-03355fd4b523)

**Comment by paul121** [comment]
Oops - easy fix. Sorry about this @aislinnpearson !
